version: '3.3'

services:
  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - symfony
  
  #memcached-client:
  #  image: memcached:alpine
  #  container_name: memcached-client
  #  command: -p 11212
  #  ports:
  #    - "11212:11212"
  #  networks:
  #    - symfonyy
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./symfony:/var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - database
    #links:
    #  - memcached-client
    #extra_hosts:
    #  - docker.host:${IP}
    networks:
      - symfony
  
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "1080:80"
      - "10443:443"
    volumes:
      - ./symfony:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - symfony

networks:
  symfony:
volumes:
  my-db: